### ISSUE TITLE
Update ember-cli-htmlbars dependency

### ISSUE THREAD

**Issue by imkikus** [mhretab/ember-cli-image-cropper#13]
Could you please update the ember-cli-htmlbars dependency since there are issues with the dependency after updating ember from `v2.6.0` to `v2.7.0`

[Deprecation Ref](https://github.com/ember-cli/ember-cli-htmlbars/issues/77)

**Comment by mhretab** [comment]
Thanks, fixed on #14

**Comment by arnaudbesnier** [comment]
Thanks for the fix, the latest package does not contain it. Can you publish a new package version ?
