### ISSUE TITLE
Component is not cleaning after itself

### ISSUE THREAD

**Issue by estshy** [mhretab/ember-cli-image-cropper#16]
Please call `$cropperContainer.destroy()` on willRemoveElement event, otherwise there is a serious memory leak.

**Comment by mhretab** [comment]
on it :) 
I will fix that and release a new version.

**Comment by estshy** [comment]
great, thank you

**Comment by mhretab** [comment]
fixed in the latest release [v0.0.9](https://github.com/mhretab/ember-cli-image-cropper/releases/tag/v0.0.9)
