### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'cropperElment.cropper.destroy()')

### ISSUE THREAD

**Issue by gponsu** [mhretab/ember-cli-image-cropper#17]
In the last version (v0.0.9), I get this error:

```
TypeError: undefined is not a function (evaluating 'cropperElment.cropper.destroy()')
```

**Comment by arnaudbesnier** [comment]
It would be great to have a new version of the package with the fix of this regression.
❤️

**Comment by Mbuckley0** [comment]
The line should be `cropperElment.cropper('destroy');` instead of `cropperElment.cropper.destroy()`

**Comment by mhretab** [comment]
Fixd in [0.0.10](https://github.com/mhretab/ember-cli-image-cropper/releases/tag/0.0.10)
