### ISSUE TITLE
I would love a little more explanation on using this component.

### ISSUE THREAD

**Issue by Jordan4jc** [mhretab/ember-cli-image-cropper#3]
I'm just having a hard time understanding how to get this working.

The documentation is a little vague, do I need to call a component in the handlebars template some where, how does the component know what action to fire if I make a new action? How do I set the source of the cropper to the source of my image?

**Comment by loganbfisher** [comment]
@Jordan4jc did you ever get this working?  I am in the same boat and I cant find much on it.

**Comment by Jordan4jc** [comment]
I'm trying to remember what I did. But knowing more about ember now than I did before I believe it seems this does not come with it's own component template, and you instead are supposed to create a new component, and instead of extending `Ember.Component` you extend this component and build on top of it. But that's just an observation of the documentation in it's current state and trying to apply what I now know about ember to it.

**Comment by loganbfisher** [comment]
Cool yeah that is what I had to do.  Thanks for the response man!
