### ISSUE TITLE
"minContainerWidth" property not included in "getProperties"

### ISSUE THREAD

**Issue by JeffLuong** [mhretab/ember-cli-image-cropper#30]
Looks like a typo, but seems like `minContainerWidth` property isn't being set upon inserting the element:

https://github.com/mhretab/ember-cli-image-cropper/blob/master/addon/components/image-cropper.js#L52

`getProperties` gets `minContainer` rather than `minContainerWidth`

**Comment by rwwagner90** [comment]
Thanks for letting us know! Would you like to open a PR to fix it perhaps?

**Comment by JeffLuong** [comment]
Done 👍 
Also realized that `toggleDragModeOnDblclick` was also misspelled...so i added a fix for that too:

 https://github.com/mhretab/ember-cli-image-cropper/pull/31
