### ISSUE TITLE
inconsistency between master branch and npm package

### ISSUE THREAD

**Issue by Romanior** [mhretab/ember-cli-image-cropper#35]
From my understanding the latest master should reflect what is published on npm. Now it is really confusing. I'm installing with `ember install ember-cli-image-cropper` which installs really outdated code with jQuery and in-compatible api.
E.g. https://ember-twiddle.com/ba1f81d311be62519a9dd74d73634f76?openFiles=twiddle.json%2Ctemplates.components.my-component.hbs
Took me a while to figure out what is going on.

I don't have a strong call to action, just warning to others, probably would face the same issue.

**Comment by rwwagner90** [comment]
Master branch is not ever guaranteed to be released for any npm package. If you look at releases, you'll see there were a bunch of commits to master since the last release. I just released a new version with what is on master, 0.0.14.

**Comment by Romanior** [comment]
ok thanks!
